language: python

os: linux
dist: xenial

jobs:
  include:
    - name: "Python 3.8 on Xenial Linux - amd64"
      python: 3.8
      arch: amd64
    - name: "Python 3.7 on Xenial Linux - amd64"
      python: 3.7
      arch: amd64
    - name: "Python 3.6 on Xenial Linux - amd64"
      python: 3.6
      arch: amd64

before_install:
  - sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - sudo echo "deb https://repos.influxdata.com/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - sudo apt update
  - sudo apt-get -y install influxdb
  - sudo systemctl enable influxdb
  - sudo systemctl start influxdb

install:
  - pip3 install -r requirements.txt

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
